//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CID { get; set; }
        public string CourseName { get; set; }
        public int StaID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
    }
}
